CREATE TABLE application_train(
  SK_ID_CURR INTEGER PRIMARY KEY,
  TARGET INTEGER,
  AMT_CREDIT NUMERIC(12,2),
  CONTRACT_TYPE VARCHAR(40)
); 

CREATE TABLE bureau(
   SK_ID_BUREAU INTEGER PRIMARY KEY,
   SK_ID_CURR INTEGER,
  FOREIGN KEY(SK_ID_CURR) REFERENCES application_train(SK_ID_CURR)
   CREDIT_ACTIVE VARCHAR(20),
   
);

CREATE TABLE previous_application(
  SK_ID_PREV INTEGER PRIMARY KEY,
  SK_ID_CURR INTEGER,
  FOREIGN KEY(SK_ID_CURR) REFERENCES application_train(SK_ID_CURR)
  AMT_ANNUITY NUMERIC(12,2), 
  NAME_CONTRACT_TYPE VARCHAR(40),

);

CREATE TABLE installments_payments(
  ID_PAYMENT INTEGER PRIMARY KEY,
  SK_ID_PREV INTEGER,
  SK_ID_CURR INTEGER,
  FOREIGN KEY(SK_ID_CURR) REFERENCES application_train(SK_ID_CURR),
  FOREIGN KEY(SK_ID_PREV) REFERENCES previous_application(SK_ID_PREV)
  DAYS_INSTALMENT INTEGER,
);
